### ISSUE TITLE
[Price] Prices of the housing types should be displayed only on the section "Disponibilités" of a "Programme" page.

### ISSUE THREAD

**Issue by lordalex** [LordAlexWorks/fw-Immoneuf#3]
**Prices of the housing types should be displayed only on the section "Disponibilités" of a "Programme" page.**

What we have now

![capture d ecran 13](https://cloud.githubusercontent.com/assets/72155/6426257/ae1652f2-bf28-11e4-8506-1611ceea6620.png)

What the client wants

![unnamed](https://cloud.githubusercontent.com/assets/72155/6426259/c7ab98ee-bf28-11e4-8b44-f728d69e48c2.png)

**Comment by Vishakha01** [comment]
I am not able to locate this.Please let me know about this page.

**Comment by bolom** [comment]
This section doesn't exist at the moment in the admin. The client wants 

* The admin selects a property
Exemple : http://lab.lordalexworks.net/wp-fwimmoneuf/programmes/quartier-arsenal-redon/

* The admin edits this property
http://lab.lordalexworks.net/wp-fwimmoneuf/wp-admin/post.php?post=2016&action=edit
* 10 text fields will be added  in this page
* Each time the admin writes something in one this field, a item will be added in section "Disponibilité"
