### ISSUE TITLE
[Dynamic Form] WP favorite Post must be added to the form.

### ISSUE THREAD

**Issue by lordalex** [LordAlexWorks/fw-Immoneuf#6]
Add the the Favourites Plug add WP Favorite Posts in the form

http://lab.lordalexworks.net/wp-fwimmoneuf/programmes/987-cantebury-drive-2/
* via le formularei

**Comment by bolom** [comment]
The client wants to see the small picture and the title

**Comment by bolom** [comment]
![thumbnail](https://cloud.githubusercontent.com/assets/72155/6438664/bd0eff28-c0a1-11e4-883a-9cb5d19cc9dd.jpg)
