### ISSUE TITLE
[favorite] The layout for the widgets on the side bar, "Mes Favoris" and "Notre Selection" must identical

### ISSUE THREAD

**Issue by lordalex** [LordAlexWorks/fw-Immoneuf#9]
Now 
![capture d ecran](https://cloud.githubusercontent.com/assets/72155/6381203/a7787322-bd15-11e4-9379-e8069c1230c4.png)

After 
![capture d ecran 3](https://cloud.githubusercontent.com/assets/72155/6381225/d775dea2-bd15-11e4-94f3-e39c6f6ed990.png)

![capture d ecran 2](https://cloud.githubusercontent.com/assets/72155/6381221/cfd4ac14-bd15-11e4-92d0-bbf33b64918d.png)

**Comment by bolom** [comment]
done
